apiVersion: v2
name: platform-mail
description: A Helm chart for deploying Stalwart Mail Server and SnappyMail with dedicated Postgres and MinIO
type: application
version: 0.1.0
appVersion: "latest"

dependencies:
  - name: postgresql
    version: "14.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: minio
    version: "14.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: minio.enabled
