apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-code-runner-package-cache
  namespace: arc-runners
  labels:
    app.kubernetes.io/name: code-code-runner-package-cache
    app.kubernetes.io/component: github-actions-runner-cache
    app.kubernetes.io/part-of: code-code
    app.kubernetes.io/managed-by: kubectl
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
