apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform-mail.fullname" . }}-stalwart
  labels:
    app.kubernetes.io/name: stalwart
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - name: smtp
      port: 25
      targetPort: smtp
      protocol: TCP
    - name: smtps
      port: 465
      targetPort: smtps
      protocol: TCP
    - name: submission
      port: 587
      targetPort: submission
      protocol: TCP
    - name: imaps
      port: 993
      targetPort: imaps
      protocol: TCP
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: stalwart
    app.kubernetes.io/instance: {{ .Release.Name }}
